# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PYTHON', 'PYTHON'), ('HTLM', 'HTML'), ('BLENDER', 'BLENDER')], default='HTML', max_length=7)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('article_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
