# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_main', '0002_resume_githuburl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='category',
            field=models.CharField(choices=[('PYTHON', 'PYTHON'), ('HTML', 'HTML'), ('BLENDER', 'BLENDER')], default='HTML', max_length=7),
        ),
    ]
