# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-11 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_main', '0003_auto_20180711_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='live_app_deployment',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
