# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-23 19:28
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_main', '0007_auto_20180723_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='article_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='image'),
        ),
    ]
